# Triggered only after MR is created/modified/closed and on main
.common_only: &common_only
  only:
    - main
    - merge_requests
    - schedules
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /\[(skip ci|ci skip|no ci)\]/i

zephyr-3.6:
  image: ubuntu:20.04
  stage: build
  <<: *common_only
  variables:
    ZEPHYR_TOOLCHAIN_VARIANT: zephyr
    RENODE_WEST_VERSION: 1.2.0
    RENODE_ZEPHYR_SDK_VERSION: 0.16.4
    RENODE_ZEPHYR_SDK: zephyr-sdk-${RENODE_ZEPHYR_SDK_VERSION}
    RENODE_ZEPHYR_SDK_FILENAME: zephyr-sdk-${RENODE_ZEPHYR_SDK_VERSION}_linux-x86_64.tar.xz
    RENODE_ZEPHYR_VERSION: v3.6.0
  before_script:
    - ./scripts/prepare_zephyr.sh
  script:
    - ./scripts/build_application.sh
  artifacts:
    paths:
      - artifacts/
