name: Build application and release

on: [push,pull_request,workflow_dispatch]

jobs:
  build_and_release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Main Zephyr repository checkout
        uses: actions/checkout@v4
        with:
          repository: zephyrproject-rtos/zephyr
          path: zephyr

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: zephyr
          toolchains: arm-zephyr-eabi

      - name: Build application
        run: ./scripts/build_application.sh
        shell: bash

      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: artifacts/software.elf
