name: Build application and release

on: [push,pull_request,workflow_dispatch]

env:
  ZEPHYR_TOOLCHAIN_VARIANT: zephyr
  RENODE_WEST_VERSION: 1.2.0
  RENODE_ZEPHYR_SDK_VERSION: 0.16.4
  RENODE_ZEPHYR_VERSION: v3.6.0

jobs:
  build_and_release:
    runs-on: ubuntu-20.04
    steps:
      - name: Set environmental variables
        run: |
          echo "RENODE_ZEPHYR_SDK=zephyr-sdk-$RENODE_ZEPHYR_SDK_VERSION" >> $GITHUB_ENV
          echo "RENODE_ZEPHYR_SDK_FILENAME=zephyr-sdk-${RENODE_ZEPHYR_SDK_VERSION}_linux-x86_64.tar.xz" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: Prepare Zephyr
        run: ./scripts/prepare_zephyr.sh
        shell: bash
      - name: Build application
        run: ./scripts/build_application.sh
        shell: bash
      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: artifacts/software.elf
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/software.elf
          asset_name: software.elf
          asset_content_type: application/octet-stream
