name: Build application and release

on: [push,pull_request,workflow_dispatch]

env:
  ZEPHYR_TOOLCHAIN_VARIANT: zephyr
  RENODE_WEST_VERSION: 1.2.0
  RENODE_ZEPHYR_SDK_VERSION: 0.16.4
  RENODE_ZEPHYR_VERSION: v3.6.0

jobs:
  build_and_release:
    runs-on: ubuntu-20.04
    steps:
      - name: Set environmental variables
        run: |
          echo "RENODE_ZEPHYR_SDK=zephyr-sdk-$RENODE_ZEPHYR_SDK_VERSION" >> $GITHUB_ENV
          echo "RENODE_ZEPHYR_SDK_FILENAME=zephyr-sdk-${RENODE_ZEPHYR_SDK_VERSION}_linux-x86_64.tar.xz" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: Prepare Zephyr
        run: ./scripts/prepare_zephyr.sh
        shell: bash
      - name: Build application
        run: ./scripts/build_application.sh
        shell: bash
      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: artifacts/software.elf
